name: k6_load_test
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  k6:
    name: k6 Load Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run k6 test
        uses: grafana/k6-action@v0.2.0
        with:
          filename: k6/scenarios/suite_name/script_suite_name.js
      - name: Upload HTML report of run tests
        uses: actions/upload-artifact@v2
        with:
          name: summary_suite_name
          path: summary_suite_name.html
          retention-days: 2  
